# Generated by Django 4.2 on 2023-04-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_conversationmessage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='converstaion',
            new_name='conversation',
        ),
    ]
